### ISSUE TITLE
Retries go into infinite loops

### ISSUE THREAD

**Issue by mbeets-entelect** [alicommit-malp/Easy-Retry#1]
Useful library but it looks like the 

public async Task Retry(Func<Task> func, RetryOptions retryOptions = null)

method will go into an infinite loop as there's nothing breaking it out on success of the function being retried.

**Comment by alicommit-malp** [comment]
The issue has been resolved, thank you for your attention and sorry for my carelessness :) 
https://www.nuget.org/packages/EasyRetry/2.0.1
